### ISSUE TITLE
SessionGuard的logout方法优化建议

### ISSUE THREAD

**Issue by visionzk** [qbhy/hyperf-auth#12]
文件：src/Guard/SessionGuard.php的logout方法
问题：logout方法先执行$this->session->has($this->sessionKey())判断存不存在，但是这个has方法存在问题。

![image](https://user-images.githubusercontent.com/16333718/96859326-f3534200-1493-11eb-8f6f-0fb396d11571.png)

hyperf中用的这个方法判断存不存在，name中带点的且为数组会判断失败（SessionGuard生成的默认sessionKey为‘auth.session‘），（get方法不会），会导致logout方法里面的的清理操作不会执行。

![image](https://user-images.githubusercontent.com/16333718/96859504-27c6fe00-1494-11eb-954d-7f4ab6b57f2d.png)

修复建议：直接执行清理操作，不用先判断存不存在

**Comment by qbhy** [comment]
合理！

**Comment by qbhy** [comment]
https://github.com/qbhy/hyperf-auth/releases/tag/v2.3 @visionzk

**Comment by visionzk** [comment]
感谢!
