### ISSUE TITLE
login($user)方法里面是拿什么字段进行验证的？

### ISSUE THREAD

**Issue by LiHouse** [qbhy/hyperf-auth#15]
login($user)方法里面是拿什么字段进行验证的？
是password吗？
user model创建的时候password要怎样加密，
![image](https://user-images.githubusercontent.com/7400970/100516384-7f0c6c80-31be-11eb-9b1e-246fcc726ee4.png)怎么才能用到这个进行password加密？

**Comment by qbhy** [comment]
@LiHouse 你截图这个是 jwt 的签名而已哦，auth 本身不参与用户实例的密码加密方式的。

**Comment by LiHouse** [comment]
@qbhy 密码验证是要自己写吗？还有，我开了redis缓存，没看到有jwt的缓存，用文件缓存也是没有，这个是存在哪？
