### ISSUE TITLE
前后台的jwt配置想要分开，是不是只能重新定义一个guard？

### ISSUE THREAD

**Issue by David-lavida** [qbhy/hyperf-auth#18]
是否可以继承authmanager？将authmanager的配置改为动态读取
![image](https://user-images.githubusercontent.com/13740095/116205828-b9c80000-a770-11eb-9420-d9396ede6cee.png)
配置通过参数传入是不是可以动态读取配置？

**Comment by qbhy** [comment]
能不能实现不说，我建议你使用不同的 guard 。 @David-lavida

**Comment by David-lavida** [comment]
> 能不能实现不说，我建议你使用不同的 guard 。 @David-lavida

为哈？是因为什么原则吗？但是使用不同的guard要重写好多方法@qbhy
