### ISSUE TITLE
实际上中间件是允许传参的，希望能后面能把中间件内的代码修改下。下面是我自己的修改

### ISSUE THREAD

**Issue by Littleboyss** [qbhy/hyperf-auth#19]
https://www.zhihu.com/zvideo/1323579441382096896
![image](https://user-images.githubusercontent.com/23073704/119291754-8c904400-bc81-11eb-9a57-3dd3f5ee1c91.png)
以上是视频里面的第三个方法，在协程的上下文中追加属性
![image](https://user-images.githubusercontent.com/23073704/119291831-bba6b580-bc81-11eb-8442-4b7c1c722a52.png)
![image](https://user-images.githubusercontent.com/23073704/119291875-d547fd00-bc81-11eb-8e5d-8a376ea4e13e.png)

**Comment by yyggg** [comment]
hy2.2 使用不了

**Comment by qbhy** [comment]
@yyggg 能具体说说怎么用不了吗 ？

**Comment by diankemao** [comment]
是否支持hyperf2.2呢？

**Comment by qbhy** [comment]
> 是否支持hyperf2.2呢？

支持的，亲测有效 @diankemao 有问题可以加群 聊 873213948

**Comment by Littleboyss** [comment]
才看到更新了，这个我自已关了
