### ISSUE TITLE
可以自定义必要声明吗

### ISSUE THREAD

**Issue by north521** [qbhy/hyperf-auth#22]
/**
     * 一些基础参数.
     */
    public function initPayload(): array
    {
        $timestamp = time();

        return [
            'sub' => '1',
            'iss' => 'http://' . ($_SERVER['SERVER_NAME'] ?? '') . ':' . ($_SERVER['SERVER_PORT'] ?? '') . ($_SERVER['REQUEST_URI'] ?? ''),
            'exp' => $timestamp + $this->getTtl(),
            'iat' => $timestamp,
            'nbf' => $timestamp,
        ];
    }

怎么自定义这里面的值？

**Comment by qbhy** [comment]
@north521 下个小版本开始支持，欢迎关注github，也可以加QQ群交流 873213948

**Comment by qbhy** [comment]
https://github.com/qbhy/hyperf-auth/releases/tag/v2.6.0 
@north521 自定义payload参考以下代码，这里的payload会覆盖默认的payload
```php
$guard->login($user, [
            'sub' => 'qbhy0715',
            'iss' => 'hyperf-auth',
        ]);
```

**Comment by north521** [comment]
怎么获取Payload（）里面的值呢，auth()->getPayload()?

**Comment by qbhy** [comment]
> 怎么获取Payload（）里面的值呢，auth()->getPayload()?
测试用例里面是这样获取的
```php
        $this->assertTrue($guard->getJwtManager()->justParse($guard->login($user, [
            'sub' => 'qbhy0715',
            'iss' => 'hyperf-auth',
        ]))->getPayload()['sub'] == 'qbhy0715');
```

**Comment by qbhy** [comment]
@north521

**Comment by qbhy** [comment]
我还是给 jwt guard 加了一个 getPayload 方法，我真是太善良了。
@north521 
https://github.com/qbhy/hyperf-auth/releases/tag/v2.6.1

**Comment by qbhy** [comment]
新的方法可以这样用 @north521 
```php
$payload = auth('jwt')->getPayload();
```

**Comment by north521** [comment]
> 新的方法可以这样用 @north521
> 
> ```
> $payload = auth('jwt')->getPayload();
> ```

非常感谢，我现在是这用的
$token = auth()->parseToken();
$payload = auth()->getJwtManager()->justParse($token)->getPayload();

**Comment by qbhy** [comment]
记得更新
