### ISSUE TITLE
缓存驱动改为redis后，在redis里查询不到数据

### ISSUE THREAD

**Issue by Double-Jin** [qbhy/hyperf-auth#23]
跟据文档上的操作把
//            'cache' => new \Doctrine\Common\Cache\FilesystemCache(sys_get_temp_dir()),             
// 如果需要分布式部署，请选择 redis 或者其他支持分布式的缓存驱动             
'cache' => function ()
 {                
  return make(Qbhy\HyperfAuth\HyperfRedisCache::class);           
    }后
    在redis里也查不到内容，请问是为什么

**Comment by qbhy** [comment]
缓存只存储黑名单内容，不会存储所有 token @Double-Jin

**Comment by Double-Jin** [comment]
那token还是存在本地文件吗,这样后面改集群不就不能用了？ @qbhy

**Comment by qbhy** [comment]
JWT 是不需要服务器存储 token 的。 @Double-Jin 
关于 jwt 的知识，可以看看我的这篇[文章 ](https://learnku.com/articles/12616/about-jwt-you-should-know)

**Comment by Double-Jin** [comment]
明了，就是说jwt的内存是存在那个加密字符串上的对吧，能解密就能拿到内容。多谢你的解答

**Comment by qbhy** [comment]
是的，不客气。那我关闭 issue 了哦，后续有问题可以进群问我，我回复率99.99999999999% @Double-Jin
