### ISSUE TITLE
过期多长时间的token可以刷新？

### ISSUE THREAD

**Issue by tieshengdetie** [qbhy/hyperf-auth#25]
![1652058041(1)](https://user-images.githubusercontent.com/23207416/167324093-0373bbcf-26db-43c4-8271-da2357ce9743.jpg)

有个疑问？ 过期多久的token可以刷新 不是应该用$payload['exp']计算么，$refreshExp = $payload['exp']+$this->getRefreshTtl()

**Comment by qbhy** [comment]
最新的代码是默认一周的，单位是秒
