### ISSUE TITLE
[BUG] sso验证方式 登陆并刷新token之后被抢线登陆不会被挤下线

### ISSUE THREAD

**Issue by Chance-fyi** [qbhy/hyperf-auth#27]
### 如图:

![image](https://user-images.githubusercontent.com/37658940/173980690-e77c0aff-1029-4985-91ec-f5c2d9e35562.png)

**Comment by qbhy** [comment]
https://github.com/qbhy/hyperf-auth/releases/tag/v2.7.1
@Chance-fyi
