### ISSUE TITLE
黑名单的过期时间认真的吗

### ISSUE THREAD

**Issue by wuqinqiang** [qbhy/hyperf-auth#3]
<img width="939" alt="屏幕快照 2020-05-27 下午11 20 11" src="https://user-images.githubusercontent.com/36129334/83039390-af891780-a070-11ea-84ef-6b2976b5b00d.png">

**Comment by qbhy** [comment]
黑名单时间确实存在些许问题，即本应存到超过 refresh 时间即可，现在是存太久了，目前这个问题已经被修复
