### ISSUE TITLE
这里要加个 null 验证吗

### ISSUE THREAD

**Issue by shuifa** [qbhy/hyperf-auth#32]
<img width="721" alt="截屏2022-10-17 16 43 42" src="https://user-images.githubusercontent.com/53784478/196132447-0fd38d84-9fbf-4a40-9a31-5da0ea8b957d.png">

如图代码的 `if (! $guard->user() instanceof Authenticatable)`这个判断。我看接口定义 `public function user(): ?Authenticatable;` 是允许返回null的。

**Comment by qbhy** [comment]
你试试 null 满不满足 instanceof Authenticatable 就知道了

**Comment by qbhy** [comment]
@shuifa

**Comment by shuifa** [comment]
> 你试试 null 满不满足 instanceof Authenticatable 就知道了

不满足

**Comment by qbhy** [comment]
那就没必要单独判断 null 了

**Comment by shuifa** [comment]
> 那就没必要单独判断 null 了

既然null不满足，那为什么接口方法还要允许返回null？？

**Comment by qbhy** [comment]
这不冲突呀，因为有可能返回 null 呗
