### ISSUE TITLE
返回的token能否在head增加alg 参数声明加密类型给其他语言解析 如go

### ISSUE THREAD

**Issue by Littleboyss** [qbhy/hyperf-auth#33]
![image](https://user-images.githubusercontent.com/23073704/197126112-bd80180e-f76e-4f27-a067-d8ff49b0f77f.png)
这个是使用hypef框架生成token
![image](https://user-images.githubusercontent.com/23073704/197126565-19160c94-9f4d-4cb1-83d1-79ccc7a25c53.png)
这个是通过github.com/golang-jwt/jwt/v4 go语言生成的token

**Comment by Littleboyss** [comment]
看到了，要自己传入打扰了

**Comment by gongzunyang** [comment]
你好 哪里传入可以alg
