### ISSUE TITLE
配置文件中使用了框架已弃用的函数方法

### ISSUE THREAD

**Issue by haodiao** [qbhy/hyperf-auth#36]
在 auth.php 中使用的 env、make 和 \Doctrine\Common\Cache\FilesystemCache 都被标注为弃用了的，建议修改为官方推荐的方法

**Comment by haodiao** [comment]
@qbhy   hyperf3.1了，你都没把 env() 和 make() 修改为 use Hyperf\Support\env 吗？
难道你用  php bin/hyperf.php gen:auth-env 不会报错吗？

**Comment by chahualao** [comment]
> @qbhy hyperf3.1了，你都没把 env() 和 make() 修改为 use Hyperf\Support\env 吗？ 难道你用 php bin/hyperf.php gen:auth-env 不会报错吗？

你提pr啊

**Comment by qbhy** [comment]
已经更新了
