### ISSUE TITLE
Hyperf 3.1

### ISSUE THREAD

**Issue by volodymyr-hordiienko** [qbhy/hyperf-auth#39]
Hi! The first of all I want to thank you for a such helpful library, its maybe the best auth library for Hyperf framework from my experience, great job! 

Interesting do you have plans to fix deprecations and upgrade library to 3.1 version?

**Comment by haozing** [comment]
+1

**Comment by vmikhav** [comment]
@volodymyr-hordiienko, @haozing prepared #40 but it need to be extended to fix all issues

**Comment by qbhy** [comment]
https://github.com/qbhy/hyperf-auth/releases/tag/v3.1.0

**Comment by volodymyr-hordiienko** [comment]
@qbhy thank you for merging #40 but i suppose not all of the issues was fixed in it as @vmikhav mentioned below
